import { Scale, MessageSquare, Users, FileText, Video } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const APP_CONFIG = {
  icon: Scale as LucideIcon,
  label: "Law",
  professionalLabel: "Lawyer",
  professionalLabelPlural: "Lawyers",
  dashboardSubtitle: "Here's an overview of your legal activity",
  dashboardDisclaimer: "Legal Disclaimer",
  dashboardDisclaimerDetail: "UniCortex provides educational legal information only. This is not legal advice.",
  dashboardCTALabel: "Ask AI",
  bookCTALabel: "Book a Consultation",
  bookingsSubtitle: "Manage your consultation appointments",
  quickActions: [
    { title: "AI Assistant", desc: "Ask a legal question", icon: MessageSquare as LucideIcon, route: "/ai-chat", color: "bg-blue-500/10 text-blue-600 dark:text-blue-400" },
    { title: "Find Lawyer", desc: "Browse verified lawyers", icon: Users as LucideIcon, route: "/lawyers", color: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" },
    { title: "Generate Document", desc: "Create legal documents", icon: FileText as LucideIcon, route: "/documents", color: "bg-purple-500/10 text-purple-600 dark:text-purple-400" },
    { title: "Legal Videos", desc: "Watch free content", icon: Video as LucideIcon, route: "/videos", color: "bg-amber-500/10 text-amber-600 dark:text-amber-400" },
  ],
  aiWelcomeTitle: "AI Legal Assistant",
  aiWelcomeDescription: "Get educational legal guidance. Ask about legal processes, your rights, document requirements, and more.",
  aiDisclaimerText: "This AI provides general legal information for educational purposes only. It does not constitute legal advice. Always consult a qualified attorney for specific legal matters.",
  aiPlaceholder: "Ask a legal question...",
  aiSuggestions: [
    "What are my tenant rights?",
    "How does small claims court work?",
    "Steps for forming an LLC",
  ],
  aiBadgeLabel: "Educational Only",
  aiFooterNote: "AI provides educational information only. Not legal advice.",
  findProfessionalTitle: "Find a Lawyer",
  findProfessionalSubtitle: "Browse verified legal professionals by specialty, rating, and availability",
  searchProfessionalPlaceholder: "Search by name or specialty...",
  specialties: [
    "All Specialties",
    "Family Law",
    "Criminal Defense",
    "Immigration",
    "Corporate Law",
    "Real Estate",
    "Employment Law",
    "Intellectual Property",
    "Personal Injury",
    "Tax Law",
    "Estate Planning",
  ],
  videosTitle: "Legal Education Videos",
  videosSubtitle: "Free educational content to help you understand legal processes",
  videoCategories: {
    "Employment": "bg-blue-500/10 text-blue-600",
    "Family Law": "bg-pink-500/10 text-pink-600",
    "Immigration": "bg-emerald-500/10 text-emerald-600",
    "Business": "bg-purple-500/10 text-purple-600",
    "Contracts": "bg-amber-500/10 text-amber-600",
    "Real Estate": "bg-teal-500/10 text-teal-600",
    "Criminal": "bg-red-500/10 text-red-600",
  },
};
